declare	
    l_parent_id number;	
    l_child_id number;	
begin	
select id_territory into l_parent_id from t_territory where moniker = 'г. Ершов';	
	select id_territory into l_child_id from t_territory where moniker = 'п. Учебный'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Полуденный'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Прудовой'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Тулайково'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'с. Антоновка';	
	select id_territory into l_child_id from t_territory where moniker = 'с. Семено-Полтавка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Южный'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'п. Целинный';	
	select id_territory into l_child_id from t_territory where moniker = 'Мирный  4 отд Декабрист'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с.Орловка(отд.01 пос.Целинный)'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Новый (3 отд.Декабрист)'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Рефлектор'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'с. Марьевка';	
	select id_territory into l_child_id from t_territory where moniker = 'с. Красный боец'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'с. Миус';	
	select id_territory into l_child_id from t_territory where moniker = 'с. Кавеленка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Нестерово'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Чкалово'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Чугунка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'с. Новая Краснянка';	
	select id_territory into l_child_id from t_territory where moniker = 'ст. Жулидово'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Лесной'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Сокорная Балка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'с. Новорепное';	
	select id_territory into l_child_id from t_territory where moniker = 'с. Орлов Гай'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Осинов Гай'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Моховое'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Новоя Слободка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'п. Новосельский';	
	select id_territory into l_child_id from t_territory where moniker = 'с. Дмитриевка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Каменая Сарма'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Коптевка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'ст. Кушумский ж/д'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Кушумский'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Лобки'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Верхний Кушум'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Михайло-Вербовка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'п. Садовый'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'КП. Чапаевка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
select id_territory into l_parent_id from t_territory where moniker = 'с. Перекопное';	
	select id_territory into l_child_id from t_territory where moniker = 'с. Александрия'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Васильевка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Еремеевка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Старая Краснянка'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Черная Падина'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
	select id_territory into l_child_id from t_territory where moniker = 'с. Чистый Плес'; update t_territory set id_parent = l_parent_id where id_territory = l_child_id;
commit;	
end;	
/	
